version: "3"
services:
  node-docker:
    build: .
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - MONGO_USER=dev
      - MONGO_PWD=pwd
      - SESSION_SECRET=secret
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    volumes:
      - mongodb:/data/db
  
  redis:
    image: redis


volumes:
  mongodb:

