version: "3"
services:
  node-docker:
    build: .
    ports:
      - "5001:4001"
    environment:
      - PORT=4001
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=pwd

