version: "3"
services:
  node-docker:
    build: .
    ports:
      - "4001:4001"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=4001
   # env_file:
   #   - ./.env